### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-css-stealing-styles-xedvDK#1]
@egillespie Can you take a look at this? It's [hosted here](https://levinsonmm.github.io/MI-449-SS17-741-css-stealing-styles-xedvDK/) and meets the following criteria:

- [x] The page includes the name of your search engine in big letters (you can make it up), with a search `input` below it, then a button below that to run the search (the button doesn't have to do anything for this prototype)
- [x] The font size of the search engine name is at least 70 pixels, so that it's very easy to see
- [x] `span` elements are wrapped around each letter of the name, like this: `<span>G</span><span>o</span><span>o</span><span>g</span><span>l</span><span>e</span>`, so that they can be styled individually with classes
- [x] The on-hover colors from the paragraphs [on this page](http://skillful-clouds.surge.sh/) are used to color individual letters of your name (similar to the letters in Google's logo)
- [x] Inspect the `input` element at the bottom of the [_Prototyping states_ page of the lesson](5) to create an identical-looking search box for your own site (it should even use the same styles on `focus`)
- [x] The styles from the "Create Account" button [on this page](http://plant-servant.surge.sh/) are used for your "Search" button (it should even use the same styles on `hover` and `active`)
- [x] There are no stylelint errors in your CSS (this will also be expected for all future projects)
- [x] All your CSS exists in a `.css` file

**Comment by egillespie** [comment]
Hi @levinsonmm, fantastic job on this project. 🎉 The code looks great and you've captured almost every style we're looking for.

The one thing that is noticeably different is the font size inside the text box. Your font size is much smaller than the one on [the sample](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/css-stealing-styles/5). Do you mind increasing your font size to match?

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by levinsonmm** [comment]
Alrighty I believe I made the necessary changes! Let me know if there is anything else I should fix, thank you!

**Comment by egillespie** [comment]
Looks great, thanks! :shipit:
